CREATE TABLE `property_seller` (
  `id` int NOT NULL AUTO_INCREMENT,
  `property_id` int NOT NULL,
  `user_id` int NOT NULL,
  `address` varchar(100) NOT NULL,
  `amount_of_contract` decimal(10,0) DEFAULT NULL,
  `title_company_closer` varchar(255) DEFAULT NULL,
  `is_earnest_money_received` tinyint(1) DEFAULT '0',
  `is_survey_received` tinyint(1) DEFAULT '0',
  `appraisal_date` datetime DEFAULT NULL,
  `appraisal_due_date` datetime DEFAULT NULL,
  `appraisal_additional_info` varchar(255) DEFAULT NULL,
  `closing_date` varchar(255) DEFAULT NULL,
  `closing_additional_info` varchar(255) DEFAULT NULL,
  `title_commitment_received_by` varchar(255) DEFAULT NULL,
  `is_cda_sent` tinyint(1) DEFAULT '0',
  `is_switch_over_utilities` tinyint(1) DEFAULT '0',
  `earnest_money_received_date` datetime DEFAULT NULL,
  `home_inspection_date` datetime DEFAULT NULL,
  `termite_inspection_date` datetime DEFAULT NULL,
  `termite_inspection_info` varchar(255) DEFAULT NULL,
  `home_inspection_info` varchar(255) DEFAULT NULL,
  `is_new_survey` tinyint(1) DEFAULT '0',
  `new_survey_info` varchar(255) DEFAULT NULL,
  `seller_name` varchar(255) DEFAULT NULL,
  `survey_due_date` datetime DEFAULT NULL,
  `is_home_warranty` tinyint(1) DEFAULT '0',
  `contract_to_lender_date` datetime DEFAULT NULL,
  `option_period_end_date` datetime DEFAULT NULL,
  `title_commit_to_be_rec_date` varchar(255) DEFAULT NULL,
  `additional_info_entire` varchar(255) DEFAULT NULL,
  `is_contract_to_lender` tinyint(1) DEFAULT '0',
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `home_warranty_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `property_id` (`property_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `property_seller_ibfk_1` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `property_seller_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user_profile` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
)
